# Julia Vrtilek
# GOAL: read all contour RDSs generated by fundamental frequency function into one dataframe per bat
# 3 Sep 2023

# load packages
library("plyr")

# load arguments from sbatch
args = commandArgs(trailingOnly=TRUE)

# set wd
setwd("/fs/ess/scratch/PAS1986/downfundfreq_DONOTOPEN")

data <- ldply(list.files(pattern = paste(".*_",args,"_T",".*_contour.RDS",sep = "")), readRDS)

saveRDS(data, paste("/fs/ess/scratch/PAS1986/down_ff_bybat/fund_freq_", args, ".RDS", sep = ""))