# Julia Vrtilek and Grace Vidaurre
# GOAL: read all energy detector logs generated by runEnergyDetector into one selection table
# 18 Aug 2021
# updated 15 Aug 2023

# load packages
library("plyr")

# set wd
setwd("/fs/ess/scratch/PAS1986")

# REMEMBER TO CHANGE PATTERN TO INCLUDE DATE
data <- ldply(list.files(pattern = "^energyDetectorLog_2023-*", recursive = TRUE), read.table, header = FALSE)

# REMEMBER TO CHANGE FILE NAME TO INCLUDE DATE
saveRDS(data, "/fs/ess/PAS1986/allEnergyDetectorLog_08-2023.RDS")
