# Julia Vrtilek
# GOAL: read all RDSs generated by spectro_analysis into one dataframe
# 27 Apr 2021

# load packages
library("plyr")

# set wd
setwd("/fs/ess/scratch/PAS1986/downSpecan")

data <- ldply(list.files(pattern = "*.RDS"), readRDS)

saveRDS(data, "/fs/ess/PAS1986/ds_giantspecan.RDS")