# Julia Vrtilek
# GOAL: read all CSVs generated by runEnergyDetector into one selection table
# 27 Apr 2021

# load packages
library("plyr")

# set wd
setwd("/fs/ess/scratch/PAS1986/selectionTables")

data <- ldply(list.files(pattern = "*.csv"), read.csv, header = TRUE)

saveRDS(data, "/fs/ess/scratch/PAS1986/selectionTables.RDS")
